app1/api/urls.py
from django.urls import path

from app1.api.views import *

app_name = 'api'
urlpatterns = [
    path('get_news/', GetNews.as_view(), name='get_news'),
]

app1/urls.py
from django.urls import include, path

from app1.views import *

app_name = 'app1'
urlpatterns = [
    path('api/', include('app1.api.urls')),
    path('', NewsListView.as_view(), name='news_list'),
    path('article/<pk>/', NewsDetailView.as_view(), name='news_detail')
]

google_news_parser/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

app1/models.py
from django.db import models


class News(models.Model):
    name = models.CharField(max_length=1000)
    url = models.URLField(max_length=400)
    template = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'news'

app1/api/views.py
import re

import requests
from bs4 import BeautifulSoup
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from app1.models import News


class GetNews(APIView):
    """
    get most recent news from first page of google news
    and store all articles as text in the db
    """
    url = 'https://news.google.com/'
    max_articles = 8  # limit number of articles to load in db

    def __init__(self, **kwargs):
        self.article_url_dict = {}
        super(GetNews, self).__init__(**kwargs)

    def get(self, request):
        """
        Delete all existing rows in News model.
        Load new articles with their names, url and content(text) into
        the db.
        """
        self.get_unique_article_urls()

        # delete all articles from News table in db
        News.objects.all().delete()

        # save all new articles to the db
        self.save_articles()

        context = {'message': 'success'}
        return Response(status=status.HTTP_200_OK, data=context)

    def get_unique_article_urls(self):
        """
        :return: scrub all article urls on self.url page
            and load unique urls along with article name
            into self.article_url_dict
        """
        content = requests.get(self.url)
        soup = BeautifulSoup(content.text, 'html.parser')
        all_links = soup.find_all('a')  # find all <a> tags
        for a in all_links:
            article_url = a.get('href')

            # if article url matches a particular format and is not none
            if article_url and re.match(r'./articles/[\w]+', article_url):
                new_url = self.url + article_url.split('./')[1]

                # only take urls that have text
                if a.text:
                    # dict will ingore duplicates
                    self.article_url_dict[new_url] = a.text

    def save_articles(self):
        """
        make get request to each article url
        and save article name, url and content as text in db
        """
        for i, a in enumerate(self.article_url_dict):

            # limit number of articles we load in db.
            if i >= self.max_articles:
                break

            response = requests.get(a)

            # only save articles that were not forbidden
            if response.status_code == 200:
                News.objects.create(
                    name=self.article_url_dict[a],
                    url=a,
                    template=response.text
                )

app1/views.py
from django.views.generic import DetailView, ListView

from app1.models import *


class NewsListView(ListView):
    template_name = 'app1/news_list.html'
    model = News


class NewsDetailView(DetailView):
    template_name = 'app1/news_detail.html'
    model = News

app1/templates/app1/news_detail.html
{{ object.template |safe}}

app1/templates/app1/news_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>News list</title>
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'app1/css/news_list.css' %}">
{% endblock css %}


{% block body %}
    <div id="idNewsListPage" class="jumbotron jumbotron-fluid">
        <div class="container ">
            <section class="text-center">
                <button class="btn btn-info btn-lg w-50"
                        v-on:click="reloadNews()" data-toggle="modal" data-target="#exampleModal"
                        data-backdrop="static" data-keyboard="false">
                    Reload News
                </button>
            </section>

            <section id="idNewsList" class="mt-4 "
                     v-bind:class="{'display-none': hideArticlesList}">
                <div class="row row-cols-lg-3  ">

                    {% for article in object_list %}

                        <div class="p-3 w-100 ">
                            <div class="p-3 btn btn-success w-100 h-100 d-flex
                                 align-items-center justify-content-center"
                                 v-on:click="articleClicked('{% url 'app1:news_detail'  article.pk %}')">

                                {{ article.name }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Processing ..</h5>

                    </div>
                    <div class="modal-body text-center">
                        <div class="spinner-border" role="status">
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
{% endblock body %}


{% block javascript %}
    <script src="{% static 'app1/js/news_list.js' %}"></script>
{% endblock javascript %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock title %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    {% block css %}
    {% endblock css %}

</head>

<body>
{% block body %}
{% endblock body %}


<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"></script>

{% block javascript %}
{% endblock javascript %}

</body>

</html>